config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :tasklists
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tasklist.rb
class Tasklist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/tasklists_controller.rb
class TasklistsController < ApplicationController

  def index
    @tasklist = Tasklist.all
  end

  def new
    @tasklist = Tasklist.new
  end

  def create
    @tasklist = Tasklist.new(tasklist_params)
    @tasklist.save 
    to_index
  end

  def edit
    @tasklist = tasklist_of_id
  end

  def update
    @tasklist = tasklist_of_id
    @tasklist.update(tasklist_params)
    to_index
  end

  def destroy
    @tasklist = tasklist_of_id
    @tasklist.delete
    to_index
  end

  private
  def tasklist_params
    params.require(:tasklist).permit(:title, :text)
  end

  def to_index
    redirect_to tasklists_path
  end

  def tasklist_of_id
    Tasklist.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Task</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasklists/_form.html.erb
<%= form_for @tasklist do |f| %>

  <div id='form'>
  <p>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </p>
  
  <p>
    <%= f.label :text %>
    <%= f.text_field :text %>
  </p>

  <%= f.submit %>
  </div>

  <div id='footer'>
  <%= link_to 'Back',  tasklists_path %>
  </div>

<% end %>

app/views/tasklists/edit.html.erb
<h2>Edit</h2>
<%= render 'form' %>

app/views/tasklists/index.html.erb
<h2>index</h2>

<% @tasklist.each do |tasklist| %>

<%= tasklist.id %>
<%= tasklist.title %>
<%= tasklist.text %> 
<%= link_to 'Edit', edit_tasklist_path(tasklist) %>
<%= link_to 'Delete', tasklist_path(tasklist), method: :delete, data:{confirm: 'ok?'} %>
<br>

<% end %>

<%= link_to 'New', new_tasklist_path %>

app/views/tasklists/new.html.erb
<h2>New</h2>
<%= render 'form' %>